title: Chris Belanger For Dayton Select Board
description: Campaign Site for Chris Belanger
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
